name: Functional Test - Open cart UI
on:
  workflow_dispatch:
    inputs:
      os:
        description: Select the OS
        type: choice
        required: false
        options:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        default: "ubuntu-latest"

      browser:
        description: "Browser"
        type: choice
        options:
          - "chrome"
          - "chromium"
          - "edge"
          - "firefox"
          - "safari"
        default: "chrome"
        required: false

      selenium-grid-url:
        description: "Selenium Grid URL (Required for headed mode execution, leave blank for headless mode)"
        type: string
        required: false

      enableRecordVideo:
        description: "Enable Video Recording"
        type: choice
        options:
          - "true"
          - "false"
        default: "false"
        required: false

      enableTracing:
        description: "Enable Tracing"
        type: choice
        options:
          - "true"
          - "false"
        default: "false"
        required: false

      tests:
        description: "Mention specific test class or method to run (i.e., TestClass1, TestClass1#testMethod1)"
        type: string
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build & Install
      run: mvn -B install -D skipTests --no-transfer-progress
    - name: Install Playwright
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
    - name: Run tests
      run: mvn test
