name: Functional Test - Open cart UI
on:
  workflow_dispatch:
    inputs:
      os:
        description: Select the OS
        type: choice
        required: false
        options:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        default: "ubuntu-latest"

      browser:
        description: "Browser"
        type: choice
        options:
          - "chrome"
          - "chromium"
          - "edge"
          - "firefox"
          - "safari"
        default: "chrome"
        required: false

      enableRecordVideo:
        description: "Enable Video Recording"
        type: choice
        options:
          - "true"
          - "false"
        default: "false"
        required: false

      enableTracing:
        description: "Enable Tracing"
        type: choice
        options:
          - "true"
          - "false"
        default: "false"
        required: false

      tests:
        description: "Mention specific test class or method to run (i.e., TestClass1, TestClass1#testMethod1)"
        type: string
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ${{github.event.inputs.os}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        browser: ${{github.event.inputs.browser}}
        enableTracing: ${{github.event.inputs.enableTracing}}
        enableRecordVideo: ${{github.event.inputs.enableRecordVideo}}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install -g playwright

    - name: Run tests
      run: mvn test
